### PR TITLE
Fix: updated package deps, change buildParser => generate for peg 0.10

### PR DESCRIPTION
**Pull request by keenahn**

### CODE REVIEW

**Comment by keenahn** [comment]
@daguej @goldibex Is this package no longer maintained?

**Comment by goldibex** [comment]
hi @keenahn, unfortunately I no longer have write access to pegjs-import as I no longer work at Casetext. I'd be happy to review, if @daguej would permit me.

**Comment by goldibex** [comment]
(hint hint @daguej)

**Comment by keenahn** [comment]
Thank you sirs! This is a package I use a lot in my peg grammars. If you are still using it at your company, you should be pleased to be using the latest version of peg.

**Comment by daguej** [comment]
@goldibex please do review -- any comments?

I'll double-check that this doesn't blow up anything on our end.

**Comment by keenahn** [comment]
Dropping this here for posterity.

We forked pegjs-import and made just that tiny change and have published to npm.

https://www.npmjs.com/package/@invisible/pegjs-import

**Pull request closed without merging**
